steps:
- name: 'bash'
  entrypoint: bash
  args: 
    - "-c"
    - "(echo I am running in a private pool! From Secret Manager: $${TEST_SECRET})"
  secretEnv:
  - TEST_SECRET
logsBucket: 'packt-cloudbuild-logging'
options:
  pool:
    name: 'projects/kenthua-test-identity/locations/us-west1/workerPools/packt-private-pool'
availableSecrets: 
  secretManager: 
    - versionName: projects/282614098327/secrets/test-secret/versions/1 
      env: TEST_SECRET